function byId(id){return document.getElementById(id)}
function n(id){return parseFloat(byId(id)?.value||0)}
function round(x){return Math.round(x*10)/10}
const menu=byId('menuBtn'),links=byId('navLinks');if(menu&&links)menu.addEventListener('click',()=>{const open=links.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));});
function html(w,s,sa,f){return '<b>Water:</b> '+round(w)+'g<br><b>Starter:</b> '+round(s)+'g<br><b>Salt:</b> '+round(sa)+'g<br><b>Total dough:</b> '+round(f+w+s+sa)+'g<br><small>Assumes a 100% hydration starter.</small>'}
function calculateHomeDough(){const f=n('homeFlour'),h=n('homeHydration'),sp=n('homeStarterPct'),salt=n('homeSaltPct');if(byId('homeDoughResult'))byId('homeDoughResult').innerHTML=html(f*h/100,f*sp/100,f*salt/100,f)}
['homeFlour','homeHydration','homeStarterPct','homeSaltPct'].forEach(id=>{if(byId(id))byId(id).addEventListener('input',calculateHomeDough)});calculateHomeDough();
function calculateDough(){const f=n('flour');byId('doughResult').innerHTML=html(f*n('hydration')/100,f*n('starterPct')/100,f*n('saltPct')/100,f)}
function calculateStarter(){const seed=n('seedStarter'),fl=seed*n('feedFlourRatio'),wa=seed*n('feedWaterRatio');byId('starterResult').innerHTML='<b>Keep starter:</b> '+round(seed)+'g<br><b>Add flour:</b> '+round(fl)+'g<br><b>Add water:</b> '+round(wa)+'g<br><b>Total starter:</b> '+round(seed+fl+wa)+'g'}
function calculateBulk(){const temp=n('temp'),str=byId('strength').value;let h=temp<=18?8.5:temp<=20?6.5:temp<=22?5:temp<=24?4:3.25;if(str==='slow')h+=1.5;if(str==='fast')h-=1;byId('bulkResult').innerHTML='<b>Estimated bulk:</b> '+Math.max(2,round(h-.75))+'-'+round(h+.75)+' hours<br><small>Judge the dough as well as the clock.</small>'}
function scaleRecipe(){const fac=n('newFlour')/n('oldFlour');byId('scaleResult').innerHTML='<b>Scale factor:</b> '+round(fac)+'x<br><b>Water:</b> '+round(n('oldWater')*fac)+'g<br><b>Salt:</b> '+round(n('oldSalt')*fac)+'g<br><b>Starter:</b> '+round(n('oldStarter')*fac)+'g'}
function bakersPercent(){const f=n('bpFlour');byId('bpResult').innerHTML='<b>Hydration:</b> '+round(n('bpWater')/f*100)+'%<br><b>Salt:</b> '+round(n('bpSalt')/f*100)+'%<br><b>Starter:</b> '+round(n('bpStarter')/f*100)+'%'}
function sampleHelper(q){byId('helperQuestion').value=q;answerHelper()}
function answerHelper(){const q=(byId('helperQuestion').value||'').toLowerCase();let a='Ask about hydration, starter amount, feeding ratios, sticky dough, weak starter, bulk fermentation, shaping, or salt.';if(q.includes('sticky')||q.includes('wet'))a='Sticky dough usually comes from high hydration, weak gluten, over-fermentation, warm dough, or rough handling. Try 65-70% hydration, add folds early in bulk, and stop bulk earlier if the dough is spreading.';else if(q.includes('hydration')||q.includes('beginner'))a='A reliable beginner hydration is 65-70%. It gives enough water for a light loaf but is still manageable on the bench.';else if(q.includes('starter')&&q.includes('how much'))a='A normal starting point is 20% starter based on flour weight. For 500g flour, that is 100g starter.';else if(q.includes('feed')||q.includes('ratio')||q.includes('1:'))a='Feeding ratios are starter : flour : water. 1:1:1 peaks fastest, 1:2:2 is a good everyday feed, and 1:5:5 gives the starter more food so it can go longer before peaking.';else if(q.includes('bulk')||q.includes('fermentation')||q.includes('ready'))a='Bulk is usually ready when the dough has risen 30-70%, looks smoother and aerated, shows bubbles around the edge, and jiggles when you move the bowl.';else if(q.includes('weak')||q.includes('not rising'))a='Feed the starter at room temperature for two or three cycles, use a ratio like 1:2:2, and bake when it reliably doubles or triples near its peak.';else if(q.includes('salt'))a='Most sourdough uses about 2% salt. For 500g flour, use 10g salt.';byId('helperAnswer').innerHTML='<b>Answer:</b><br>'+a}
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('service-worker.js').catch(()=>{}))}