
function byId(id){return document.getElementById(id)}function n(id){return parseFloat(byId(id)?.value||0)}function round(x){return Math.round(x*10)/10}
const m=byId("menuBtn"),l=byId("navLinks");if(m)m.addEventListener("click",()=>l.classList.toggle("open"));
function html(w,s,sa,f){return `<b>Water:</b> ${round(w)}g<br><b>Starter:</b> ${round(s)}g<br><b>Salt:</b> ${round(sa)}g<br><b>Total dough:</b> ${round(f+w+s+sa)}g`}
function calculateHomeDough(){const f=n("homeFlour"),h=n("homeHydration"),sp=n("homeStarterPct"),salt=n("homeSaltPct");if(byId("homeDoughResult"))byId("homeDoughResult").innerHTML=html(f*h/100,f*sp/100,f*salt/100,f)}
["homeFlour","homeHydration","homeStarterPct","homeSaltPct"].forEach(id=>{if(byId(id))byId(id).addEventListener("input",calculateHomeDough)});calculateHomeDough();
function calculateDough(){const f=n("flour");byId("doughResult").innerHTML=html(f*n("hydration")/100,f*n("starterPct")/100,f*n("saltPct")/100,f)}
function calculateStarter(){const seed=n("seedStarter"),fl=seed*n("feedFlourRatio"),wa=seed*n("feedWaterRatio");byId("starterResult").innerHTML=`<b>Keep starter:</b> ${round(seed)}g<br><b>Add flour:</b> ${round(fl)}g<br><b>Add water:</b> ${round(wa)}g<br><b>Total starter:</b> ${round(seed+fl+wa)}g`}
function calculateBulk(){const temp=n("temp"),str=byId("strength").value;let h=temp<=18?8.5:temp<=20?6.5:temp<=22?5:temp<=24?4:3.25;if(str==="slow")h+=1.5;if(str==="fast")h-=1;byId("bulkResult").innerHTML=`<b>Estimated bulk:</b> ${Math.max(2,round(h-.75))}–${round(h+.75)} hours<br><small>Judge the dough as well as the clock.</small>`}
function scaleRecipe(){const fac=n("newFlour")/n("oldFlour");byId("scaleResult").innerHTML=`<b>Scale factor:</b> ${round(fac)}×<br><b>Water:</b> ${round(n("oldWater")*fac)}g<br><b>Salt:</b> ${round(n("oldSalt")*fac)}g<br><b>Starter:</b> ${round(n("oldStarter")*fac)}g`}
function bakersPercent(){const f=n("bpFlour");byId("bpResult").innerHTML=`<b>Hydration:</b> ${round(n("bpWater")/f*100)}%<br><b>Salt:</b> ${round(n("bpSalt")/f*100)}%<br><b>Starter:</b> ${round(n("bpStarter")/f*100)}%`}
function sampleHelper(q){byId("helperQuestion").value=q;answerHelper()}
function answerHelper(){const q=(byId("helperQuestion").value||"").toLowerCase();let a="Ask about hydration, starter amount, feeding ratios, sticky dough, bulk fermentation, or salt.";if(q.includes("sticky")||q.includes("wet"))a="Sticky dough is usually caused by high hydration, weak gluten, over-fermentation, or not enough flour on your hands. Try 65–70% hydration and more folds.";else if(q.includes("hydration")||q.includes("beginner"))a="A good beginner hydration is 65–70%. It is easier to shape than 75–80% dough.";else if(q.includes("starter")&&q.includes("how much"))a="A common starter amount is 20% of flour weight. For 500g flour, use about 100g starter.";else if(q.includes("feed")||q.includes("ratio")||q.includes("1:"))a="Ratios are starter : flour : water. 1:1:1 is fast, 1:2:2 is everyday, and 1:5:5 lasts longer.";else if(q.includes("bulk")||q.includes("fermentation")||q.includes("ready"))a="Bulk is ready when the dough is puffier, airy, bubbly at the edges and jiggles slightly.";else if(q.includes("salt"))a="Most sourdough uses about 2% salt. For 500g flour, use about 10g salt.";byId("helperAnswer").innerHTML=`<b>Answer:</b><br>${a}`}
if("serviceWorker" in navigator){window.addEventListener("load",()=>navigator.serviceWorker.register("service-worker.js").catch(()=>{}))}
