function byId(id){return document.getElementById(id)}
function n(id){return parseFloat(byId(id)?.value||0)}
function round(x){return Math.round(x*10)/10}
const menu=byId('menuBtn'),links=byId('navLinks');if(menu&&links)menu.addEventListener('click',()=>{const open=links.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));});
function html(w,s,sa,f){return '<b>Water:</b> '+round(w)+'g<br><b>Starter:</b> '+round(s)+'g<br><b>Salt:</b> '+round(sa)+'g<br><b>Total dough:</b> '+round(f+w+s+sa)+'g<br><small>Assumes a 100% hydration starter.</small>'}
function calculateHomeDough(){const f=n('homeFlour'),h=n('homeHydration'),sp=n('homeStarterPct'),salt=n('homeSaltPct');if(byId('homeDoughResult'))byId('homeDoughResult').innerHTML=html(f*h/100,f*sp/100,f*salt/100,f)}
['homeFlour','homeHydration','homeStarterPct','homeSaltPct'].forEach(id=>{if(byId(id))byId(id).addEventListener('input',calculateHomeDough)});calculateHomeDough();
function calculateDough(){const f=n('flour');byId('doughResult').innerHTML=html(f*n('hydration')/100,f*n('starterPct')/100,f*n('saltPct')/100,f)}
function calculateStarter(){const seed=n('seedStarter'),fl=seed*n('feedFlourRatio'),wa=seed*n('feedWaterRatio');byId('starterResult').innerHTML='<b>Keep starter:</b> '+round(seed)+'g<br><b>Add flour:</b> '+round(fl)+'g<br><b>Add water:</b> '+round(wa)+'g<br><b>Total starter:</b> '+round(seed+fl+wa)+'g'}
function calculateBulk(){const temp=n('temp'),str=byId('strength').value;let h=temp<=18?8.5:temp<=20?6.5:temp<=22?5:temp<=24?4:3.25;if(str==='slow')h+=1.5;if(str==='fast')h-=1;byId('bulkResult').innerHTML='<b>Estimated bulk:</b> '+Math.max(2,round(h-.75))+'-'+round(h+.75)+' hours<br><small>Judge the dough as well as the clock.</small>'}
function scaleRecipe(){const fac=n('newFlour')/n('oldFlour');byId('scaleResult').innerHTML='<b>Scale factor:</b> '+round(fac)+'x<br><b>Water:</b> '+round(n('oldWater')*fac)+'g<br><b>Salt:</b> '+round(n('oldSalt')*fac)+'g<br><b>Starter:</b> '+round(n('oldStarter')*fac)+'g'}
function bakersPercent(){const f=n('bpFlour');byId('bpResult').innerHTML='<b>Hydration:</b> '+round(n('bpWater')/f*100)+'%<br><b>Salt:</b> '+round(n('bpSalt')/f*100)+'%<br><b>Starter:</b> '+round(n('bpStarter')/f*100)+'%'}
const helperAnswers=[
{keys:['sticky','wet','slack','soupy'],title:'Sticky or slack dough',answer:'Sticky dough usually comes from high hydration, weak gluten, warm dough, over-fermentation, or rough handling. Try 65-70% hydration, add folds during the first half of bulk, wet your hands instead of adding lots of bench flour, and shape earlier if the dough is spreading.'},
{keys:['dense','tight crumb','heavy','brick'],title:'Dense loaf',answer:'A dense loaf is usually under-fermented, made with a weak starter, shaped too aggressively, or baked before enough gas developed. Make sure your starter doubles reliably, extend bulk until the dough is aerated, and avoid degassing heavily during shaping.'},
{keys:['gummy','gum','wet crumb','underbaked'],title:'Gummy crumb',answer:'Gummy crumb can come from under-baking, slicing while hot, too much water for the flour, or fermentation issues. Bake until deeply coloured, cool at least 2 hours, and try reducing hydration by 3-5 points if the loaf stays tacky.'},
{keys:['starter amount','how much starter','inoculation'],title:'Starter amount',answer:'A good default is 20% starter based on flour weight. Use 10-15% for warmer rooms or slower schedules, 20% for everyday bakes, and 25-30% for cool rooms or faster same-day dough.'},
{keys:['hydration','beginner hydration','water percentage'],title:'Hydration',answer:'A reliable beginner hydration is 65-70%. Move higher only when your flour and shaping can handle it. If dough spreads or sticks everywhere, reduce water before changing everything else.'},
{keys:['feed','feeding','ratio','1:1:1','1:2:2','1:5:5'],title:'Feeding ratios',answer:'Feeding ratios are starter : flour : water. 1:1:1 peaks quickly, 1:2:2 is a good everyday feed, and 1:5:5 gives the starter more food and a longer window before it peaks.'},
{keys:['hooch','grey liquid','gray liquid','black liquid'],title:'Hooch on starter',answer:'Grey or dark liquid is usually hooch, a sign the starter is hungry or has been left too long. Pour it off, keep a small amount of starter, and feed regularly for a few cycles. If you see fuzzy mould or pink/orange streaks, discard it.'},
{keys:['mold','mould','pink','orange','fuzzy'],title:'Mould or unsafe starter',answer:'Fuzzy mould, pink streaks, orange streaks, or a smell that is truly repulsive are signs to throw the starter away and clean the jar. Normal sour, fruity, yogurt-like or light vinegar smells can be revived with regular feeding.'},
{keys:['float test','ready starter','starter ready','bubbly'],title:'Starter readiness',answer:'Starter is ready when it has risen strongly after feeding, shows bubbles through the jar, smells pleasantly tangy or fruity, and is near its peak. The float test can help, but visible rise and reliable timing matter more.'},
{keys:['bulk','fermentation','ready dough','rise percent'],title:'Bulk fermentation',answer:'Bulk is usually ready when dough has risen about 30-70%, looks smoother and aerated, has bubbles around the edge, and jiggles when the bowl moves. Warmer dough and higher starter percentages need less rise before shaping.'},
{keys:['over fermented','overproof','over proof','collapsed'],title:'Over-fermentation',answer:'Over-fermented dough feels slack, sticky and fragile, spreads after shaping, and may bake flat. Next time reduce bulk time, lower starter percentage, keep the dough cooler, or reduce hydration slightly.'},
{keys:['under fermented','underproof','under proof'],title:'Under-fermentation',answer:'Under-fermented dough feels dense and tight, resists shaping, and often bakes with a tight crumb or tunnels. Give bulk more time, use a stronger starter, or keep the dough warmer.'},
{keys:['cold proof','retard','fridge','refrigerate'],title:'Cold proofing',answer:'Cold proofing slows fermentation and develops flavour. Shape first, place in a floured banneton, cover well, and refrigerate. Many loaves bake well after 8-16 hours cold, but very warm or over-bulked dough may need less time.'},
{keys:['dutch oven','steam','covered bake'],title:'Steam and Dutch ovens',answer:'Steam keeps the crust flexible while the loaf expands. A preheated Dutch oven traps steam well. Bake covered for the first part of the bake, then uncover to colour the crust.'},
{keys:['score','scoring','ear','blade'],title:'Scoring',answer:'Score cold dough with a sharp lame or razor at a shallow angle for an ear. If cuts drag, chill the dough longer, flour the surface lightly, and use one confident slash instead of many hesitant cuts.'},
{keys:['oven spring','flat loaf','spread'],title:'Oven spring',answer:'Weak oven spring can come from weak starter, under-fermentation, over-fermentation, poor shaping tension, not enough steam, or an oven that is not hot enough. Fix one variable at a time: starter strength first, then bulk timing, then shaping.'},
{keys:['salt','forgot salt','too salty'],title:'Salt',answer:'Most sourdough uses about 2% salt. For 500g flour, use 10g. If you forgot salt, the dough may ferment faster and taste flat; bake it anyway, then use it for toast or croutons.'},
{keys:['autolyse','fermentolyse'],title:'Autolyse',answer:'Autolyse means resting flour and water before adding salt and starter. It helps gluten development and extensibility. Fermentolyse includes the starter during the rest. For beginners, a 20-40 minute rest is plenty.'},
{keys:['stretch and fold','coil fold','folds'],title:'Folds',answer:'Folds build strength without kneading. Do 3-4 sets during the first half of bulk, spaced 20-40 minutes apart. Stop once the dough is smoother, elastic and holding shape.'},
{keys:['whole wheat','wholemeal','rye','spelt'],title:'Whole grain flour',answer:'Whole wheat and rye absorb more water and ferment quickly because they bring more minerals and enzymes. Start by replacing 10-20% of the white flour, then adjust water and timing gradually.'},
{keys:['discard','sourdough discard'],title:'Discard',answer:'Discard is unfed starter removed before feeding. It is not waste if you use it in pancakes, crackers, waffles or flatbreads, but it will not reliably raise bread unless it is active and recently fed.'},
{keys:['sour','more sour','less sour','flavour','flavor'],title:'Sourness',answer:'For more sourness, try a longer cold proof, a slightly stiffer starter, or some whole grain flour. For milder bread, use a younger starter near peak, warmer fermentation, and avoid letting the starter collapse before mixing.'},
{keys:['blisters','crust','thin crust','hard crust'],title:'Crust',answer:'Small crust blisters often come from cold proofing and good steam. A very hard crust may come from over-baking or cooling in a dry oven; a soft crust may need more uncovered baking time.'},
{keys:['banneton','sticking','stuck'],title:'Dough sticking to banneton',answer:'Use rice flour or a rice/wheat flour blend in the banneton. Let the shaped dough build surface tension, dust the top before turning out, and avoid over-proofing until the dough is wet and fragile.'}
];
function sampleHelper(q){byId('helperQuestion').value=q;answerHelper()}
function answerHelper(){const q=(byId('helperQuestion').value||'').toLowerCase();let matches=helperAnswers.filter(item=>item.keys.some(k=>q.includes(k)));if(!matches.length)matches=[{title:'General sourdough answer',answer:'For most sourdough problems, check four things in order: starter strength, dough temperature, fermentation level, and hydration. A strong starter, moderate hydration, and careful bulk timing solve more issues than changing many ingredients at once.'}];byId('helperAnswer').innerHTML=matches.slice(0,3).map(item=>'<b>'+item.title+'</b><br>'+item.answer).join('<hr>')+'<br><small>For deeper context, see the troubleshooting and starter maintenance guides.</small>'}
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('service-worker.js').catch(()=>{}))}